defaultPlacement: end
descriptionFormat: '{product.title} - {title}'
enableVersioning: false
handle: cookiePackage
hasDimensions: false
hasProductTitleField: true
hasVariantTitleField: true
isStructure: false
maxLevels: null
maxVariants: null
name: 'Cookie — Package'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary product page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
productFieldLayouts:
  b443e063-3cd3-485f-8695-eb6b63bdd872:
    cardThumbAlignment: end
    cardView:
      - defaultSku
      - defaultPrice
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-09-13T01:29:50+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\commerce\fieldlayoutelements\ProductTitleField
            uid: c54e26ee-9ecc-4094-add0-885eabe4ab48
            userCondition: null
            warning: null
            width: 100
          -
            attribute: variants
            dateAdded: '2026-09-13T01:29:50+00:00'
            elementCondition: null
            id: null
            instructions: null
            label: null
            mandatory: true
            orientation: null
            requirable: false
            required: false
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\VariantsField
            uid: bcde3542-5451-4ab7-aaa4-a23df64c4ecf
            userCondition: null
            warning: null
          -
            dateAdded: '2026-09-13T02:52:39+00:00'
            elementCondition: null
            heading: Defaults
            type: craft\fieldlayoutelements\Heading
            uid: effaa9ca-21dc-4e3a-8a78-e39a6b64725c
            userCondition: null
          -
            dateAdded: '2026-09-13T02:52:39+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: c2d9c750-d7f6-412a-822c-7571172f15a5 # Image(s)
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6af062c2-3893-4ab8-b582-00b2320e1360
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-09-13T02:52:39+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 64e2bf73-506f-4e6f-9a22-dd5d54f10b77 # Rich Text Editor
            handle: productInfo
            instructions: null
            label: 'Product Info'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f0a995ab-6874-45c8-bb0a-0af1f8502ca3
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: c4b7215a-039d-4c15-9d04-0c961ad24033
        userCondition: null
    thumbFieldKey: null
productTitleFormat: ''
productTitleTranslationKeyFormat: null
productTitleTranslationMethod: site
productUiLabelFormat: '{title}'
propagationMethod: all
showSlugField: true
siteSettings:
  2589bc8f-a277-4da6-ae5f-f294f779bc87: # charlies
    enabledByDefault: true
    hasUrls: true
    template: shop/product.twig
    uriFormat: ' products/cookies/{slug}'
skuFormat: ''
slugTranslationKeyFormat: null
slugTranslationMethod: site
variantFieldLayouts:
  db64b76f-4dbe-49c3-a286-486d6fb29c09:
    cardThumbAlignment: end
    cardView:
      - sku
      - priceView
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-09-13T01:29:50+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\commerce\fieldlayoutelements\VariantTitleField
            uid: 4edabafd-e40c-4347-9d98-6709c81deeed
            userCondition: null
            warning: null
            width: 100
          -
            attribute: sku
            dateAdded: '2026-09-13T01:29:50+00:00'
            elementCondition: null
            id: null
            instructions: null
            label: null
            mandatory: true
            orientation: null
            requirable: false
            required: true
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasableSkuField
            uid: 839543bc-9539-4d92-89b7-413571013335
            userCondition: null
            warning: null
            width: 100
          -
            attribute: price
            dateAdded: '2026-09-13T01:29:50+00:00'
            elementCondition: null
            id: null
            instructions: null
            label: __blank__
            mandatory: true
            orientation: null
            requirable: false
            required: true
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasablePriceField
            uid: 4d1b635d-0615-4d1e-8537-16611a982bbc
            userCondition: null
            warning: null
            width: 100
          -
            attribute: stock
            dateAdded: '2026-09-13T01:29:50+00:00'
            defaultAllowOutOfStockPurchases: false
            defaultInventoryTracked: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            mandatory: true
            orientation: null
            requirable: false
            required: false
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasableStockField
            uid: 9fa2774f-ade3-42f8-80bb-b961a9e30b79
            userCondition: null
            warning: null
            width: 100
          -
            attribute: availableForPurchase
            dateAdded: '2026-09-13T01:29:50+00:00'
            defaultAvailableForPurchase: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            mandatory: true
            orientation: null
            requirable: false
            required: false
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasableAvailableForPurchaseField
            uid: 83c69309-40ad-47f0-9a2c-9b9106c09d41
            userCondition: null
            warning: null
            width: 100
          -
            attribute: allowedQty
            dateAdded: '2026-09-13T01:29:50+00:00'
            elementCondition: null
            id: null
            instructions: null
            label: null
            mandatory: true
            orientation: null
            requirable: false
            required: false
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasableAllowedQtyField
            uid: d48a250d-a845-46b2-848d-367873c18146
            userCondition: null
            warning: null
            width: 100
          -
            attribute: freeShipping
            dateAdded: '2026-09-13T01:29:50+00:00'
            elementCondition: null
            id: null
            instructions: null
            label: null
            mandatory: true
            orientation: null
            requirable: false
            required: false
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasableFreeShippingField
            uid: f5ee7f98-c808-4854-bdfd-3da6dc0ec1b3
            userCondition: null
            warning: null
            width: 100
          -
            attribute: promotable
            dateAdded: '2026-09-13T01:29:50+00:00'
            defaultPromotable: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            mandatory: true
            orientation: null
            requirable: false
            required: false
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasablePromotableField
            uid: bc01c0f8-5661-43e9-8823-32fa4911e956
            userCondition: null
            warning: null
            width: 100
          -
            attribute: dimensions
            dateAdded: '2026-09-13T01:29:50+00:00'
            elementCondition: null
            id: null
            instructions: null
            label: null
            mandatory: true
            orientation: null
            requirable: false
            required: false
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasableDimensionsField
            uid: 905afc1c-a055-4d56-809c-fc8fe1dc8314
            userCondition: null
            warning: null
            width: 100
          -
            attribute: weight
            dateAdded: '2026-09-13T01:29:50+00:00'
            elementCondition: null
            id: null
            instructions: null
            label: null
            mandatory: true
            orientation: null
            requirable: false
            required: false
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasableWeightField
            uid: 45dfbc8b-37ba-4fe3-a49f-7784d9fd0ac4
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0a2e7620-5d51-4d79-9e48-1acc0e0f6b7d
        userCondition: null
    thumbFieldKey: null
variantTitleFormat: '{product.title}'
variantTitleTranslationKeyFormat: null
variantTitleTranslationMethod: site
variantUiLabelFormat: '{title}'
