defaultPlacement: end
descriptionFormat: '{product.title} - {title}'
enableVersioning: false
handle: cookie2Pack
hasDimensions: false
hasProductTitleField: true
hasVariantTitleField: true
isStructure: false
maxLevels: null
maxVariants: null
name: 'Cookie — 2 pack'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary product page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
productFieldLayouts:
  8a1bc3be-6bc4-4af8-b57f-8cd59f020807:
    cardThumbAlignment: end
    cardView:
      - defaultSku
      - defaultPrice
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-09-13T01:30:29+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\commerce\fieldlayoutelements\ProductTitleField
            uid: cf3522ba-6706-47fa-9667-8d002e37aa43
            userCondition: null
            warning: null
            width: 100
          -
            attribute: variants
            dateAdded: '2026-09-13T01:30:29+00:00'
            elementCondition: null
            id: null
            instructions: null
            label: null
            mandatory: true
            orientation: null
            requirable: false
            required: false
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\VariantsField
            uid: 40a3e442-6bc6-406d-869b-c8d38f5e9dff
            userCondition: null
            warning: null
        name: Content
        uid: 6635d90e-9100-4364-8817-9f4be153103c
        userCondition: null
    thumbFieldKey: null
productTitleFormat: ''
productTitleTranslationKeyFormat: null
productTitleTranslationMethod: site
productUiLabelFormat: '{title}'
propagationMethod: all
showSlugField: true
siteSettings:
  2589bc8f-a277-4da6-ae5f-f294f779bc87: # charlies
    enabledByDefault: true
    hasUrls: true
    template: shop/product.twig
    uriFormat: ' products/cookies/{slug}'
skuFormat: ''
slugTranslationKeyFormat: null
slugTranslationMethod: site
variantFieldLayouts:
  35ef756b-6ee1-48e6-9bb2-b795cc040f30:
    cardThumbAlignment: end
    cardView:
      - sku
      - priceView
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-09-13T01:30:29+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\commerce\fieldlayoutelements\VariantTitleField
            uid: 7780fa20-dac1-4f6a-9340-9821e0de0bea
            userCondition: null
            warning: null
            width: 100
          -
            attribute: sku
            dateAdded: '2026-09-13T01:30:29+00:00'
            elementCondition: null
            id: null
            instructions: null
            label: null
            mandatory: true
            orientation: null
            requirable: false
            required: true
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasableSkuField
            uid: b5573c5e-238f-4929-a8c0-b1ee78a966f5
            userCondition: null
            warning: null
            width: 100
          -
            attribute: price
            dateAdded: '2026-09-13T01:30:29+00:00'
            elementCondition: null
            id: null
            instructions: null
            label: __blank__
            mandatory: true
            orientation: null
            requirable: false
            required: true
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasablePriceField
            uid: 3cd16902-fbe9-4864-b788-565659b9a2d1
            userCondition: null
            warning: null
            width: 100
          -
            attribute: stock
            dateAdded: '2026-09-13T01:30:29+00:00'
            defaultAllowOutOfStockPurchases: false
            defaultInventoryTracked: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            mandatory: true
            orientation: null
            requirable: false
            required: false
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasableStockField
            uid: df1d6008-5dc6-44dd-8a77-3b174bb684ae
            userCondition: null
            warning: null
            width: 100
          -
            attribute: availableForPurchase
            dateAdded: '2026-09-13T01:30:29+00:00'
            defaultAvailableForPurchase: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            mandatory: true
            orientation: null
            requirable: false
            required: false
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasableAvailableForPurchaseField
            uid: 81572b9c-45c8-41cd-85a6-26d618156fc4
            userCondition: null
            warning: null
            width: 100
          -
            attribute: allowedQty
            dateAdded: '2026-09-13T01:30:29+00:00'
            elementCondition: null
            id: null
            instructions: null
            label: null
            mandatory: true
            orientation: null
            requirable: false
            required: false
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasableAllowedQtyField
            uid: 8dd81b89-c2a5-4f2d-a859-32d2f70b5ae2
            userCondition: null
            warning: null
            width: 100
          -
            attribute: freeShipping
            dateAdded: '2026-09-13T01:30:29+00:00'
            elementCondition: null
            id: null
            instructions: null
            label: null
            mandatory: true
            orientation: null
            requirable: false
            required: false
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasableFreeShippingField
            uid: d57ad597-7fbd-4edc-8c0e-2c649d66a5ba
            userCondition: null
            warning: null
            width: 100
          -
            attribute: promotable
            dateAdded: '2026-09-13T01:30:29+00:00'
            defaultPromotable: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            mandatory: true
            orientation: null
            requirable: false
            required: false
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasablePromotableField
            uid: d6458578-50f3-4ae2-90e2-a2ab1007b9a6
            userCondition: null
            warning: null
            width: 100
          -
            attribute: dimensions
            dateAdded: '2026-09-13T01:30:29+00:00'
            elementCondition: null
            id: null
            instructions: null
            label: null
            mandatory: true
            orientation: null
            requirable: false
            required: false
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasableDimensionsField
            uid: 39a977e2-d7b9-4a4f-9217-1bb098d02c47
            userCondition: null
            warning: null
            width: 100
          -
            attribute: weight
            dateAdded: '2026-09-13T01:30:29+00:00'
            elementCondition: null
            id: null
            instructions: null
            label: null
            mandatory: true
            orientation: null
            requirable: false
            required: false
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasableWeightField
            uid: dfa3dc61-286e-45f7-9ce7-0225d90c4df5
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f2474ca2-85dd-436b-a919-6dc89a8b2d01
        userCondition: null
    thumbFieldKey: null
variantTitleFormat: '{product.title}'
variantTitleTranslationKeyFormat: null
variantTitleTranslationMethod: site
variantUiLabelFormat: '{title}'
