defaultPlacement: end
descriptionFormat: '{product.title} - {title}'
enableVersioning: false
handle: genderRevealCake
hasDimensions: false
hasProductTitleField: true
hasVariantTitleField: true
isStructure: false
maxLevels: null
maxVariants: 1
name: 'Gender Reveal Cake'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary product page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
productFieldLayouts:
  caca12e2-2291-4a8e-b590-789015517dce:
    cardThumbAlignment: end
    cardView:
      - defaultSku
      - defaultPrice
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-09-13T01:27:40+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\commerce\fieldlayoutelements\ProductTitleField
            uid: 8c243781-c6db-438f-868e-c1e1b37b724c
            userCondition: null
            warning: null
            width: 100
          -
            attribute: variants
            dateAdded: '2026-09-13T01:27:40+00:00'
            elementCondition: null
            id: null
            instructions: null
            label: null
            mandatory: true
            orientation: null
            requirable: false
            required: false
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\VariantsField
            uid: 693dae71-5a34-4271-841e-4ad67d890618
            userCondition: null
            warning: null
          -
            dateAdded: '2026-09-13T02:46:29+00:00'
            elementCondition: null
            heading: Defaults
            type: craft\fieldlayoutelements\Heading
            uid: c64f0666-4f2c-454f-b8e2-85a3827069d8
            userCondition: null
          -
            dateAdded: '2026-09-13T02:46:29+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: c2d9c750-d7f6-412a-822c-7571172f15a5 # Image(s)
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b48a11ca-fd56-4b64-9c2b-fa8d8b791b7a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-09-13T02:46:29+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 64e2bf73-506f-4e6f-9a22-dd5d54f10b77 # Rich Text Editor
            handle: productInfo
            instructions: null
            label: 'Product Info'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 716acf00-865b-4bab-9f28-d95f102352ad
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 31102699-3a87-4765-96ad-c014cb11d87a
        userCondition: null
    thumbFieldKey: null
productTitleFormat: ''
productTitleTranslationKeyFormat: null
productTitleTranslationMethod: site
productUiLabelFormat: '{title}'
propagationMethod: all
showSlugField: true
siteSettings:
  2589bc8f-a277-4da6-ae5f-f294f779bc87: # charlies
    enabledByDefault: true
    hasUrls: true
    template: shop/product.twig
    uriFormat: 'products/cakes/{slug}'
skuFormat: ''
slugTranslationKeyFormat: null
slugTranslationMethod: site
variantFieldLayouts:
  36ea9922-3f21-4605-95d1-25d81744ee67:
    cardThumbAlignment: end
    cardView:
      - sku
      - priceView
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-09-13T01:27:40+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\commerce\fieldlayoutelements\VariantTitleField
            uid: 652c2120-faed-4da4-b697-c766f50bff90
            userCondition: null
            warning: null
            width: 100
          -
            attribute: sku
            dateAdded: '2026-09-13T01:27:40+00:00'
            elementCondition: null
            id: null
            instructions: null
            label: null
            mandatory: true
            orientation: null
            requirable: false
            required: true
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasableSkuField
            uid: f85b7aca-10d3-48aa-9b69-7ed05d8ed00b
            userCondition: null
            warning: null
            width: 100
          -
            attribute: price
            dateAdded: '2026-09-13T01:27:40+00:00'
            elementCondition: null
            id: null
            instructions: null
            label: __blank__
            mandatory: true
            orientation: null
            requirable: false
            required: true
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasablePriceField
            uid: 3f126c54-ddce-4beb-807d-1a150bf38594
            userCondition: null
            warning: null
            width: 100
          -
            attribute: stock
            dateAdded: '2026-09-13T01:27:40+00:00'
            defaultAllowOutOfStockPurchases: false
            defaultInventoryTracked: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            mandatory: true
            orientation: null
            requirable: false
            required: false
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasableStockField
            uid: 016046d6-de35-46b1-ae11-be47e34878fc
            userCondition: null
            warning: null
            width: 100
          -
            attribute: availableForPurchase
            dateAdded: '2026-09-13T01:27:40+00:00'
            defaultAvailableForPurchase: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            mandatory: true
            orientation: null
            requirable: false
            required: false
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasableAvailableForPurchaseField
            uid: e4541350-8267-4533-afce-cac0a3278012
            userCondition: null
            warning: null
            width: 100
          -
            attribute: allowedQty
            dateAdded: '2026-09-13T01:27:40+00:00'
            elementCondition: null
            id: null
            instructions: null
            label: null
            mandatory: true
            orientation: null
            requirable: false
            required: false
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasableAllowedQtyField
            uid: 5e65f874-c2f5-46a3-a61c-9dd9aa4449ec
            userCondition: null
            warning: null
            width: 100
          -
            attribute: freeShipping
            dateAdded: '2026-09-13T01:27:40+00:00'
            elementCondition: null
            id: null
            instructions: null
            label: null
            mandatory: true
            orientation: null
            requirable: false
            required: false
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasableFreeShippingField
            uid: 5e7d18d9-efa4-4214-9878-83c3e32883b2
            userCondition: null
            warning: null
            width: 100
          -
            attribute: promotable
            dateAdded: '2026-09-13T01:27:40+00:00'
            defaultPromotable: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            mandatory: true
            orientation: null
            requirable: false
            required: false
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasablePromotableField
            uid: a96579bf-edb7-44eb-a53e-ca0d9564f909
            userCondition: null
            warning: null
            width: 100
          -
            attribute: dimensions
            dateAdded: '2026-09-13T01:27:40+00:00'
            elementCondition: null
            id: null
            instructions: null
            label: null
            mandatory: true
            orientation: null
            requirable: false
            required: false
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasableDimensionsField
            uid: 531155f4-6be8-466f-80c0-55711d95692e
            userCondition: null
            warning: null
            width: 100
          -
            attribute: weight
            dateAdded: '2026-09-13T01:27:40+00:00'
            elementCondition: null
            id: null
            instructions: null
            label: null
            mandatory: true
            orientation: null
            requirable: false
            required: false
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasableWeightField
            uid: 3c4277f2-7cd5-4d56-a38e-0fafa1ca905f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: fa9cee37-a5c1-4c38-9931-7a00a1bba79d
        userCondition: null
    thumbFieldKey: null
variantTitleFormat: '{product.title}'
variantTitleTranslationKeyFormat: null
variantTitleTranslationMethod: site
variantUiLabelFormat: '{title}'
