defaultPlacement: end
descriptionFormat: '{product.title} - {title}'
enableVersioning: false
handle: treatsPeanutButterBacon
hasDimensions: false
hasProductTitleField: true
hasVariantTitleField: true
isStructure: false
maxLevels: null
maxVariants: 2
name: 'Treats — Peanut Butter Bacon'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary product page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
productFieldLayouts:
  b7641a60-36c6-4ca7-801e-9f668da3a334:
    cardThumbAlignment: end
    cardView:
      - defaultSku
      - defaultPrice
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-09-13T01:28:16+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\commerce\fieldlayoutelements\ProductTitleField
            uid: 819b4e75-17ec-47cb-9d62-7bb0bd73e7ed
            userCondition: null
            warning: null
            width: 100
          -
            attribute: variants
            dateAdded: '2026-09-13T01:28:16+00:00'
            elementCondition: null
            id: null
            instructions: null
            label: null
            mandatory: true
            orientation: null
            requirable: false
            required: false
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\VariantsField
            uid: 310986af-529a-4c0f-8e65-2c404a172d1b
            userCondition: null
            warning: null
          -
            dateAdded: '2026-09-13T02:48:15+00:00'
            elementCondition: null
            heading: Defaults
            type: craft\fieldlayoutelements\Heading
            uid: 95f888e9-cdb4-47e5-acc3-c33ebe7a1caf
            userCondition: null
          -
            dateAdded: '2026-09-13T02:48:15+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: c2d9c750-d7f6-412a-822c-7571172f15a5 # Image(s)
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 25a84e67-e11d-45f7-98c1-eb1780f117be
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-09-13T02:48:15+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 64e2bf73-506f-4e6f-9a22-dd5d54f10b77 # Rich Text Editor
            handle: productInfo
            instructions: null
            label: 'Product Info'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 96e17fac-bdfe-4a75-9afb-b4bdbbe813a7
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 06868a39-e735-4cba-914e-0b6ee2663349
        userCondition: null
    thumbFieldKey: null
productTitleFormat: ''
productTitleTranslationKeyFormat: null
productTitleTranslationMethod: site
productUiLabelFormat: '{title}'
propagationMethod: all
showSlugField: true
siteSettings:
  2589bc8f-a277-4da6-ae5f-f294f779bc87: # charlies
    enabledByDefault: true
    hasUrls: true
    template: shop/product.twig
    uriFormat: ' products/treats/{slug}'
skuFormat: ''
slugTranslationKeyFormat: null
slugTranslationMethod: site
variantFieldLayouts:
  ef36fafa-97ec-47f3-8eee-00b90e2b68c6:
    cardThumbAlignment: end
    cardView:
      - sku
      - priceView
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-09-13T01:28:16+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\commerce\fieldlayoutelements\VariantTitleField
            uid: ab5b95a6-f3c3-4fce-be21-32db0310dcf2
            userCondition: null
            warning: null
            width: 100
          -
            attribute: sku
            dateAdded: '2026-09-13T01:28:16+00:00'
            elementCondition: null
            id: null
            instructions: null
            label: null
            mandatory: true
            orientation: null
            requirable: false
            required: true
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasableSkuField
            uid: fda7f889-8672-4588-8f8d-96ef92d4d0a0
            userCondition: null
            warning: null
            width: 100
          -
            attribute: price
            dateAdded: '2026-09-13T01:28:16+00:00'
            elementCondition: null
            id: null
            instructions: null
            label: __blank__
            mandatory: true
            orientation: null
            requirable: false
            required: true
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasablePriceField
            uid: 912df02c-1df2-459f-996e-f29b7fcd3d2f
            userCondition: null
            warning: null
            width: 100
          -
            attribute: stock
            dateAdded: '2026-09-13T01:28:16+00:00'
            defaultAllowOutOfStockPurchases: false
            defaultInventoryTracked: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            mandatory: true
            orientation: null
            requirable: false
            required: false
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasableStockField
            uid: 2badbcf6-ff4d-4cd3-8e70-c296d5f9836d
            userCondition: null
            warning: null
            width: 100
          -
            attribute: availableForPurchase
            dateAdded: '2026-09-13T01:28:16+00:00'
            defaultAvailableForPurchase: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            mandatory: true
            orientation: null
            requirable: false
            required: false
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasableAvailableForPurchaseField
            uid: ec9cb70f-9ecf-438a-a239-cbefbb40b27f
            userCondition: null
            warning: null
            width: 100
          -
            attribute: allowedQty
            dateAdded: '2026-09-13T01:28:16+00:00'
            elementCondition: null
            id: null
            instructions: null
            label: null
            mandatory: true
            orientation: null
            requirable: false
            required: false
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasableAllowedQtyField
            uid: 835fde21-4541-4913-bc23-31884d5c7dd2
            userCondition: null
            warning: null
            width: 100
          -
            attribute: freeShipping
            dateAdded: '2026-09-13T01:28:16+00:00'
            elementCondition: null
            id: null
            instructions: null
            label: null
            mandatory: true
            orientation: null
            requirable: false
            required: false
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasableFreeShippingField
            uid: 5acf4f37-b8cf-4557-93f2-200229d98b65
            userCondition: null
            warning: null
            width: 100
          -
            attribute: promotable
            dateAdded: '2026-09-13T01:28:16+00:00'
            defaultPromotable: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            mandatory: true
            orientation: null
            requirable: false
            required: false
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasablePromotableField
            uid: 3c352e45-2977-41cd-a4c2-098c8c1ee945
            userCondition: null
            warning: null
            width: 100
          -
            attribute: dimensions
            dateAdded: '2026-09-13T01:28:16+00:00'
            elementCondition: null
            id: null
            instructions: null
            label: null
            mandatory: true
            orientation: null
            requirable: false
            required: false
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasableDimensionsField
            uid: 44fdf837-6de1-4e91-b5cb-8048dda02cdb
            userCondition: null
            warning: null
            width: 100
          -
            attribute: weight
            dateAdded: '2026-09-13T01:28:16+00:00'
            elementCondition: null
            id: null
            instructions: null
            label: null
            mandatory: true
            orientation: null
            requirable: false
            required: false
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasableWeightField
            uid: 91128e6f-25d7-45d0-930e-9a3f75808c15
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 2f6883a7-d5d3-40fd-8cd3-1606a40c8cc0
        userCondition: null
    thumbFieldKey: null
variantTitleFormat: '{product.title}'
variantTitleTranslationKeyFormat: null
variantTitleTranslationMethod: site
variantUiLabelFormat: '{title}'
