defaultPlacement: end
descriptionFormat: '{product.title} - {title}'
enableVersioning: false
handle: treatsApplePeanutButter
hasDimensions: false
hasProductTitleField: true
hasVariantTitleField: true
isStructure: false
maxLevels: null
maxVariants: 2
name: 'Treats — Apple Peanut Butter'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary product page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
productFieldLayouts:
  2f943535-f840-482d-ac7c-1237055711f4:
    cardThumbAlignment: end
    cardView:
      - defaultSku
      - defaultPrice
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-09-13T01:27:56+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\commerce\fieldlayoutelements\ProductTitleField
            uid: c662d571-82a1-48d0-a52c-963039c80c3f
            userCondition: null
            warning: null
            width: 100
          -
            attribute: variants
            dateAdded: '2026-09-13T01:27:56+00:00'
            elementCondition: null
            id: null
            instructions: null
            label: null
            mandatory: true
            orientation: null
            requirable: false
            required: false
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\VariantsField
            uid: 8c435f43-43c0-4219-b077-92bd58d106c3
            userCondition: null
            warning: null
          -
            dateAdded: '2026-09-13T02:47:22+00:00'
            elementCondition: null
            heading: DEfaults
            type: craft\fieldlayoutelements\Heading
            uid: 48915c0e-73c5-4a08-ba68-d47a112c56f8
            userCondition: null
          -
            dateAdded: '2026-09-13T02:47:22+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: c2d9c750-d7f6-412a-822c-7571172f15a5 # Image(s)
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a03a28b3-de83-4e54-ab2d-cce329a017bc
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-09-13T02:47:22+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 64e2bf73-506f-4e6f-9a22-dd5d54f10b77 # Rich Text Editor
            handle: productInfo
            instructions: null
            label: 'Product Info'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 31a32684-2b32-4876-b2d8-eb82312387af
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: cd3e07f4-d699-443b-8b89-441a17518953
        userCondition: null
    thumbFieldKey: null
productTitleFormat: ''
productTitleTranslationKeyFormat: null
productTitleTranslationMethod: site
productUiLabelFormat: '{title}'
propagationMethod: all
showSlugField: true
siteSettings:
  2589bc8f-a277-4da6-ae5f-f294f779bc87: # charlies
    enabledByDefault: true
    hasUrls: true
    template: shop/product.twig
    uriFormat: ' products/treats/{slug}'
skuFormat: ''
slugTranslationKeyFormat: null
slugTranslationMethod: site
variantFieldLayouts:
  d0ca86fc-8b17-43c5-b1bc-c5e8ed6cbe7b:
    cardThumbAlignment: end
    cardView:
      - sku
      - priceView
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-09-13T01:27:56+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\commerce\fieldlayoutelements\VariantTitleField
            uid: ccabdbf9-cf46-4630-8423-bd221c247828
            userCondition: null
            warning: null
            width: 100
          -
            attribute: sku
            dateAdded: '2026-09-13T01:27:56+00:00'
            elementCondition: null
            id: null
            instructions: null
            label: null
            mandatory: true
            orientation: null
            requirable: false
            required: true
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasableSkuField
            uid: f0eb4b11-1f7e-4ccf-b9e0-fecdc049eda2
            userCondition: null
            warning: null
            width: 100
          -
            attribute: price
            dateAdded: '2026-09-13T01:27:56+00:00'
            elementCondition: null
            id: null
            instructions: null
            label: __blank__
            mandatory: true
            orientation: null
            requirable: false
            required: true
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasablePriceField
            uid: 10ff0acb-934c-4837-b4df-fb30acc0c051
            userCondition: null
            warning: null
            width: 100
          -
            attribute: stock
            dateAdded: '2026-09-13T01:27:56+00:00'
            defaultAllowOutOfStockPurchases: false
            defaultInventoryTracked: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            mandatory: true
            orientation: null
            requirable: false
            required: false
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasableStockField
            uid: 1660495f-252c-4032-a76d-4d69197eed13
            userCondition: null
            warning: null
            width: 100
          -
            attribute: availableForPurchase
            dateAdded: '2026-09-13T01:27:56+00:00'
            defaultAvailableForPurchase: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            mandatory: true
            orientation: null
            requirable: false
            required: false
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasableAvailableForPurchaseField
            uid: 265aeabe-cc40-4a77-b184-ac9b65cc7d4b
            userCondition: null
            warning: null
            width: 100
          -
            attribute: allowedQty
            dateAdded: '2026-09-13T01:27:56+00:00'
            elementCondition: null
            id: null
            instructions: null
            label: null
            mandatory: true
            orientation: null
            requirable: false
            required: false
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasableAllowedQtyField
            uid: 5a4ed73f-5120-4c7c-917f-14b5ccbe21d8
            userCondition: null
            warning: null
            width: 100
          -
            attribute: freeShipping
            dateAdded: '2026-09-13T01:27:56+00:00'
            elementCondition: null
            id: null
            instructions: null
            label: null
            mandatory: true
            orientation: null
            requirable: false
            required: false
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasableFreeShippingField
            uid: 7c648fb1-942c-4cfe-a521-cf55b0c398cc
            userCondition: null
            warning: null
            width: 100
          -
            attribute: promotable
            dateAdded: '2026-09-13T01:27:56+00:00'
            defaultPromotable: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            mandatory: true
            orientation: null
            requirable: false
            required: false
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasablePromotableField
            uid: 1a4265b0-67c2-428e-8b31-9bf74531e1cd
            userCondition: null
            warning: null
            width: 100
          -
            attribute: dimensions
            dateAdded: '2026-09-13T01:27:56+00:00'
            elementCondition: null
            id: null
            instructions: null
            label: null
            mandatory: true
            orientation: null
            requirable: false
            required: false
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasableDimensionsField
            uid: 2528b163-c0cb-48ae-ba7b-5edcf0e811fd
            userCondition: null
            warning: null
            width: 100
          -
            attribute: weight
            dateAdded: '2026-09-13T01:27:56+00:00'
            elementCondition: null
            id: null
            instructions: null
            label: null
            mandatory: true
            orientation: null
            requirable: false
            required: false
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasableWeightField
            uid: ee6b9028-b568-45c5-b09a-f072327dc6af
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 14a0486c-0607-4ba3-887f-39bbdc278b02
        userCondition: null
    thumbFieldKey: null
variantTitleFormat: '{product.title}'
variantTitleTranslationKeyFormat: null
variantTitleTranslationMethod: site
variantUiLabelFormat: '{title}'
