allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  51fcd5e0-7cbc-4b96-b884-b89b44ddb102:
    cardThumbAlignment: end
    cardView:
      - 'layoutElement:e3942894-6a0e-4466-a692-dcc48b5ab7c1'
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-09-20T01:47:35+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 4d7ec46f-500b-47b6-8eba-f2f42e8066c1 # Plain Text
            handle: label
            instructions: null
            label: Label
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e3942894-6a0e-4466-a692-dcc48b5ab7c1
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-09-20T01:47:35+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 4d7ec46f-500b-47b6-8eba-f2f42e8066c1 # Plain Text
            handle: placeholder
            instructions: null
            label: Placeholder
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5c253345-50dc-42fc-970a-52059fb14a8f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-09-20T01:47:35+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: c3351fca-dd41-4318-b6ed-7ea1f921ca34 # lighswitch
            handle: required
            instructions: null
            label: Required
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 22f477fc-e814-4491-95f6-23105f178b3e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ea52abf4-b295-448b-9574-0addfadb9ba5
        userCondition: null
    thumbFieldKey: null
handle: textarea
hasTitleField: false
icon: null
name: Textarea
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
