columnSuffix: null
handle: color
instructions: null
name: Color
searchable: false
settings:
  options:
    -
      label: White
      value: white
      default: '1'
    -
      label: Charcoal
      value: charcoal
      default: ''
    -
      label: Teal
      value: teal
      default: ''
    -
      label: Bronze
      value: bronze
      default: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
