columnSuffix: null
handle: color
instructions: null
name: Color
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - White
        -
          - value
          - white
        -
          - icon
          - ''
        -
          - color
          - '#ffffff'
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Charcoal
        -
          - value
          - charcoal
        -
          - icon
          - ''
        -
          - color
          - '#29323d'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Teal
        -
          - value
          - teal
        -
          - icon
          - ''
        -
          - color
          - '#0ed3c8'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Bronze
        -
          - value
          - bronze
        -
          - icon
          - ''
        -
          - color
          - '#b67236'
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
