columnSuffix: null
handle: productCarouselBlock
instructions: null
name: 'Block — Product Carousel'
searchable: false
settings:
  viewMode: grouped
translationKeyFormat: null
translationMethod: site
type: craft\fields\ContentBlock
