dateModified: 1778554907
email:
  fromEmail: jerry@charliesbarkery.com
  fromName: charlies
  transportType: craft\mail\transportadapters\Sendmail
fs:
  amazonFileSystem:
    hasUrls: true
    name: 'Amazon File System'
    settings:
      addSubfolderToRootUrl: true
      autoFocalPoint: false
      bucket: charliesecom
      bucketSelectionMode: choose
      cfDistributionId: ''
      cfPrefix: ''
      expires: ''
      keyId: $AMAZON_ACCESS_KEY
      makeUploadsPublic: true
      region: us-east-2
      secret: $AMAZON_SECRET_KEY
      storageClass: ''
      subfolder: $AMAZON_SUBPATH
    type: craft\awss3\Fs
    url: $AMAZON_BASE_URL
meta:
  __names__:
    0c390a43-79fb-43af-89ea-7b8a7c41d3d7: 'Page Blocks Entry' # Page Blocks Entry
    4d7ec46f-500b-47b6-8eba-f2f42e8066c1: 'Plain Text' # Plain Text
    5eec91ac-9cac-40d5-915a-f973014bad60: 'Link Field' # Link Field
    7c4edaa8-604a-48d2-a947-3388823e3b2b: Color # Color
    8a0ba0e6-6a25-4da5-afdb-887f84ffdf4f: Dummy # Dummy
    46d1905d-56db-493d-90c0-5de9d9910388: 'Block — Split Section' # Block — Split Section
    64e2bf73-506f-4e6f-9a22-dd5d54f10b77: 'Rich Text Editor' # Rich Text Editor
    69d4a3e4-5d6a-4e7f-8108-3ce57d5a8fc2: New # New
    0119d5ec-bfd1-4692-a006-407e05e36d20: 'Block — Product Carousel' # Block — Product Carousel
    645bb423-5466-4a2c-a05f-ceeb31bac6e5: Primary # Primary
    2589bc8f-a277-4da6-ae5f-f294f779bc87: charlies # charlies
    29323bbb-b103-4d28-aafb-f37b64ee4ae3: 'Block Type' # Block Type
    62025e7c-d31e-4ea1-a778-df0457c8317a: 'Entry — Card Matrix' # Entry — Card Matrix
    226774f0-df25-4716-be27-d89522bf600c: 'Contact Form' # Contact Form
    6671498f-b940-4c47-a8d5-1de96b0bd763: 'Block — Card Grid' # Block — Card Grid
    a8354a78-8bd4-4740-a1e5-99da6ee4e9bd: Pages # Pages
    b7d4b92a-3550-4709-ba61-d7e4d3829f54: 'Entry — Page' # Entry — Page
    b7f30bd9-4da3-41f0-8d17-26a2a6a0bf46: 'Home Page' # Home Page
    ba77b7b1-a2e0-4dee-9e20-4dfafe54e7c8: Uploads # Uploads
    bb71e142-3e9f-4467-9d03-43e288eb4bc0: 'Matrix — Cards' # Matrix — Cards
    c2d9c750-d7f6-412a-822c-7571172f15a5: Image(s) # Image(s)
    c58d7339-c7da-48b0-a338-3835c34549f1: New # New
    c3351fca-dd41-4318-b6ed-7ea1f921ca34: lighswitch # lighswitch
    d2dbcdc7-ca53-408a-8df4-99d795133201: 'Block — Hero' # Block — Hero
    d79efc26-fed5-43e6-bce8-1d7e7f9846b9: charlies # charlies
    dc36f051-fd02-4e59-bf63-204e8eccf224: 'Block — Call To Action' # Block — Call To Action
    e91396d1-d7c4-4b1b-a3e9-55972a84ff9c: 'Block Picker' # Block Picker
plugins:
  aws-s3:
    edition: standard
    enabled: true
    schemaVersion: '2.0'
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 5.0.0.1
  commerce:
    edition: pro
    enabled: true
    licenseKey: 0U6EFPB4B0QWVBY8YV3X7TOY
    schemaVersion: 5.6.0.0
  formie:
    edition: standard
    enabled: true
    licenseKey: 2QPGV31GRB42B2ILZYYO957N
    schemaVersion: 3.4.12
  vite:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: pro
  live: true
  name: charlies
  schemaVersion: 5.9.0.8
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
